[[breaking]]
title = ""
description = ""

[[features]]
title = "New resource"
description = "`oxide_silo_saml_identity_provider` [#442](https://github.com/oxidecomputer/terraform-provider-oxide/pull/442)."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = "`oxide_vpc_firewall_rules`"
description = "Fixed the `Failed to decode resource from state` error when upgrading the provider to v0.13.0. [#501](https://github.com/oxidecomputer/terraform-provider-oxide/pull/501)"
